pattern_list = ['Bullish_Flag',
                'Bearish_Flag',
                'Bullish_Pennant',
                'Bearish_Pennant',
                'Ascending_Triangle',
                'Descending_Triangle',
                'Bullish_Channel',
                'Bearish_Channel',
                'Horizontal_Channel',
                'Cup_with_Handle',
                'Symmetrical_Triangle',
                'Rectangle',
                'Double_Top',
                'Double_Bottom',
                'Head_and_Shoulders',
                'Inverse_Head_and_Shoulders',
                'Diamond_Top',
                'Falling_Wedge',
                'Rising_Wedge',
                'Rounding_Bottom',
                'Triple_Top',
                'Triple_Bottom',
                'Bump_and_Run',
                'Megaphone'
                ]

